Updated MCU's
project-generator/project_generator_definitions pull request #149
Opened 2021-06-06 18:13 UTC by heezes

Added two more MCU's to the list
[#]Stm32l462ve
[#]Bluenrg2

2021-06-07 12:29 UTC, 0xc0170 requested changes

2021-06-07 12:29 UTC, 0xc0170 commented on project_generator_definitions/mcu/st/bluenrg2.yaml
> +    vendor:
this is not MCU , not required to be here. you can create our own project with this board and just use the MCU you are adding below ?

2021-06-07 12:29 UTC, 0xc0170 commented on project_generator_definitions/mcu/st/stm32l462ve.yaml
> +        - cortex-m4
can you add a new line here

2021-06-10 12:34 UTC, heezes commented
@0xc0170 Recent commit has the requested changes

2021-06-15 08:12 UTC, 0xc0170 approved these changes

2021-06-15 08:12 UTC, 0xc0170 commented
Travis is not running, they changed their plans. I'll create an issue and move it elsewhere 🤦

2021-06-15 08:12 UTC, merged